### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [freeshrugsxd/qgis-monokai-pro-spectrum#1]
# Problem

How different is the functionality offered in settings?
![settings](https://user-images.githubusercontent.com/2510900/108810216-558f9100-75b3-11eb-987c-62491d65619e.png)

**Comment by freeshrugsxd** [comment]
Hey,

there is no new functionality in this plugin. It is a Color Scheme which you can select from the Color scheme combobox. Since QGIS offers no way to import/export or save (more than one) custom color schemes, I had to manually recreate this color scheme multiple times already. I found [Nyall Dawson's color scheme plugin](https://github.com/nyalldawson/qgis_theme_monokai) and thought it was a nice way to import and share custom schemes.

**Comment by NyakudyaA** [comment]
@Gustry What do you think about this plugin?

**Comment by Gustry** [comment]
This is ok for me.

It's for now maybe the only way to add a theme AFAIK.

**Comment by freeshrugsxd** [comment]
Thank you guys for the approval!
